services:
  backend:
    build:
      context: backend
    image: memocha-backend
    container_name: memocha-backend
    tty: True
    ports:
      - 8055:8000
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LOG_LEVEL: ${LOG_LEVEL}
    networks:
      - memocha

  db:
    image: postgres:15
    container_name: memocha-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - memocha

networks:
  memocha:
    external: True
