services:
  backend:
    build:
      context: backend
    image: memocha-backend
    container_name: memocha-backend
    tty: True
    ports:
      - 8055:8000
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LOG_LEVEL: ${LOG_LEVEL}

networks:
  memocha:
    external: True